version: '3'
# Special testing Vector container.  No data volumes are exposed for
# simplicity however ssh port 22 is available for EMA testing

services:
  vector:
    image: actian/vectortest
    build: . 
    container_name: vector
    restart: "no"
    ports:
      - "2222:22"
      - 27832:27832
      - 27839:27839
    secrets:
       - source: vector_test_docker_id_rsa_pub
         target: id_rsa_pub

secrets:
  vector_test_docker_id_rsa:
     file: $PWD/id_rsa
  vector_test_docker_id_rsa_pub:
     file: $PWD/id_rsa.pub
